# Generated by Django 3.1.4 on 2020-12-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201210_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('primary_interest', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('personal_image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
